// <auto-generated />
using System;
using CleanArchitecture.Dav.Infrastructure.DbsContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanArchitecture.Dav.Infrastructure.Migrations
{
    [DbContext(typeof(CleanArchitectureDbContext))]
    [Migration("20260602200051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Dav.Domain.Livres.Entities.Emprunt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateEmprunt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateRetour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdLivre")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUtilisateur")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LivreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdLivre")
                        .IsUnique();

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("LivreId");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("CleanArchitecture.Dav.Domain.Livres.Entities.Livre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("CleanArchitecture.Dav.Domain.Utilisateurs.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("CleanArchitecture.Dav.Domain.Livres.Entities.Emprunt", b =>
                {
                    b.HasOne("CleanArchitecture.Dav.Domain.Livres.Entities.Livre", null)
                        .WithOne("Emprunt")
                        .HasForeignKey("CleanArchitecture.Dav.Domain.Livres.Entities.Emprunt", "IdLivre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Dav.Domain.Utilisateurs.Entities.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Dav.Domain.Livres.Entities.Livre", null)
                        .WithMany("HistoriqueEmprunts")
                        .HasForeignKey("LivreId");
                });

            modelBuilder.Entity("CleanArchitecture.Dav.Domain.Livres.Entities.Livre", b =>
                {
                    b.Navigation("Emprunt");

                    b.Navigation("HistoriqueEmprunts");
                });
#pragma warning restore 612, 618
        }
    }
}
